// <auto-generated />
using System;
using EcommerceStarter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceStarter.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251116_MigrateStripeToApiConfigurations")]
    partial class MigrateStripeToApiConfigurations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // This is a data migration - the model remains unchanged
            // All tables and entities are defined in the previous migrations

#pragma warning restore 612, 618
        }
    }
}
