using EcommerceStarter.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EcommerceStarter.Pages.Admin.Settings
{
    [Authorize(Roles = "Admin")]
    public class ApiTestingModel : PageModel
    {
        private readonly ISiteSettingsService _settingsService;
        private readonly IEncryptionService _encryptionService;
        private readonly ILogger<ApiTestingModel> _logger;

        public ApiTestingModel(
            ISiteSettingsService settingsService,
            IEncryptionService encryptionService,
            ILogger<ApiTestingModel> logger)
        {
            _settingsService = settingsService;
            _encryptionService = encryptionService;
            _logger = logger;
        }

        public string ServiceKey { get; set; } = string.Empty;
        public bool IsEnabled { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            var settings = await _settingsService.GetSettingsAsync();
            
            IsEnabled = settings.EnableInternalServiceAuth;
            
            if (!string.IsNullOrEmpty(settings.InternalServiceKeyEncrypted))
            {
                try
                {
                    ServiceKey = _encryptionService.Decrypt(settings.InternalServiceKeyEncrypted);
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "Failed to decrypt internal service key");
                    ServiceKey = "[Decryption Error]";
                }
            }

            return Page();
        }

        public async Task<IActionResult> OnPostToggleAuthAsync(bool enable)
        {
            try
            {
                var settings = await _settingsService.GetSettingsAsync();
                settings.EnableInternalServiceAuth = enable;

                // If enabling for the first time and no key exists, generate one
                if (enable && string.IsNullOrEmpty(settings.InternalServiceKeyEncrypted))
                {
                    var newKey = Guid.NewGuid().ToString();
                    settings.InternalServiceKeyEncrypted = _encryptionService.Encrypt(newKey);
                    _logger.LogInformation("Generated new internal service key");
                }

                await _settingsService.UpdateSettingsAsync(settings, User.Identity?.Name);

                TempData["SuccessMessage"] = enable 
                    ? "Internal service authentication enabled" 
                    : "Internal service authentication disabled";
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to toggle internal service authentication");
                TempData["ErrorMessage"] = "Failed to update settings. Please try again.";
            }

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostRegenerateKeyAsync()
        {
            try
            {
                var settings = await _settingsService.GetSettingsAsync();
                
                var newKey = Guid.NewGuid().ToString();
                settings.InternalServiceKeyEncrypted = _encryptionService.Encrypt(newKey);

                await _settingsService.UpdateSettingsAsync(settings, User.Identity?.Name);

                _logger.LogWarning("Internal service key regenerated by {User}", User.Identity?.Name);
                TempData["SuccessMessage"] = "New service key generated successfully. Update your test scripts with the new key.";
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to regenerate internal service key");
                TempData["ErrorMessage"] = "Failed to regenerate key. Please try again.";
            }

            return RedirectToPage();
        }
    }
}
